#!/bin/bash
set -euo pipefail

# bootstrap.sh — one-shot host provisioning for a fresh EAH box.
#
# Target: Ubuntu 24.04 LTS on a fresh VPS — arch-agnostic. Works on amd64
# (DigitalOcean droplet, the current host) and arm64 (Oracle Ampere A1).
# Reproduces the host layer that lives OUTSIDE docker-compose:
#   - Docker Engine + compose plugin
#   - MariaDB server, loopback-bound, with the `eah` database + app user
#   - cloudflared, installed as a systemd service (the ONLY public path)
#   - ~/eah/.env with generated secrets (DB password, SESSION_SECRET)
#
# After this, deploy the app from your laptop:
#   DEPLOY_HOST=enaih ./deploy.sh
#
# Networking model (see CLAUDE.md + deploy notes): cloudflared dials OUT to
# Cloudflare on 7844; nothing connects in. We deliberately open ZERO ingress
# ports and never touch Oracle's baked-in iptables rules. MariaDB stays on
# 127.0.0.1; the eah container reaches it via network_mode: host.
#
# Usage (run ON the fresh box, as the default `ubuntu` user):
#   # 1. copy this file over (scp, or paste), then:
#   TUNNEL_TOKEN='eyJ...'  ./bootstrap.sh
#
#   TUNNEL_TOKEN is the token from the Cloudflare dashboard for a remote-managed
#   tunnel (Zero Trust → Networks → Tunnels → create → "cloudflared" → copy the
#   token out of the install command). Omit it to install the binary but skip
#   the service (you can run `sudo cloudflared service install <token>` later).
#
# Re-runnable: existing .env is reused (not clobbered); DB user/db use IF NOT
# EXISTS; package installs are idempotent.

# ---- config (override via env) ---------------------------------------------
APP_DIR="${APP_DIR:-$HOME/eah}"
DB_NAME="${DB_NAME:-eah}"
DB_USER="${DB_USER:-eah}"
TUNNEL_TOKEN="${TUNNEL_TOKEN:-}"

log() { printf '\n\033[1;36m==> %s\033[0m\n' "$*"; }

log "host arch: $(dpkg --print-architecture)"  # amd64 (DO) or arm64 (Oracle) both fine

# ---- 1. base packages ------------------------------------------------------
log "apt update + base packages"
sudo apt-get update -y
# age: encrypts DB backups at creation (scripts/backup-db.sh). s3cmd: off-box
# Spaces upload. Both are host-side ops tooling, not app/container deps.
sudo apt-get install -y ca-certificates curl gnupg openssl age s3cmd

# ---- 2. Docker Engine + compose plugin (official repo) ---------------------
if ! command -v docker >/dev/null 2>&1; then
  log "installing Docker Engine + compose plugin"
  sudo install -m 0755 -d /etc/apt/keyrings
  sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  sudo chmod a+r /etc/apt/keyrings/docker.asc
  echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
    | sudo tee /etc/apt/sources.list.d/docker.list >/dev/null
  sudo apt-get update -y
  sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  sudo usermod -aG docker "$USER"
  echo "NOTE: added $USER to the docker group — log out/in (or 'newgrp docker')"
  echo "      before 'docker' works without sudo. deploy.sh over SSH gets a"
  echo "      fresh login each time, so it's fine there."
else
  log "Docker already present — skipping"
fi
sudo systemctl enable --now docker

# ---- 3. MariaDB (loopback-bound) + app db/user -----------------------------
log "installing MariaDB server"
sudo apt-get install -y mariadb-server
sudo systemctl enable --now mariadb

# Ubuntu's MariaDB already binds 127.0.0.1 by default; assert it so a future
# package default can't silently expose the port.
if ! grep -rqs '^bind-address\s*=\s*127.0.0.1' /etc/mysql/; then
  log "pinning MariaDB bind-address to 127.0.0.1"
  echo -e "[mysqld]\nbind-address = 127.0.0.1" \
    | sudo tee /etc/mysql/mariadb.conf.d/99-eah-loopback.cnf >/dev/null
  sudo systemctl restart mariadb
fi

# ---- 4. .env (generate secrets once, reuse thereafter) ---------------------
mkdir -p "$APP_DIR"
ENV_FILE="$APP_DIR/.env"
if [[ -f "$ENV_FILE" ]]; then
  log ".env exists — reusing its DB credentials"
  # Extract specific keys instead of `source`-ing: the file is docker env_file
  # format (e.g. EMAIL_FROM has unquoted spaces/<>), which is NOT valid bash.
  get_env() { grep -E "^$1=" "$ENV_FILE" | head -n1 | cut -d= -f2-; }
  DB_NAME="$(get_env DB_NAME)"; DB_NAME="${DB_NAME:-eah}"
  DB_USER="$(get_env DB_USER)"; DB_USER="${DB_USER:-eah}"
  DB_PASSWORD="$(get_env DB_PASSWORD)"
  : "${DB_PASSWORD:?existing .env has no DB_PASSWORD — fix it or remove .env}"
else
  log "generating $ENV_FILE with fresh secrets"
  DB_PASSWORD="$(openssl rand -hex 24)"
  SESSION_SECRET="$(openssl rand -hex 32)"
  cat > "$ENV_FILE" <<EOF
# generated by bootstrap.sh $(date -u +%Y-%m-%dT%H:%M:%SZ) — edit freely.
# Optional integrations (Resend / Discord / Google) left blank; fill in later.

PORT=8090
HOST=127.0.0.1
NODE_ENV=production

DB_HOST=127.0.0.1
DB_PORT=3306
DB_USER=$DB_USER
DB_PASSWORD=$DB_PASSWORD
DB_NAME=$DB_NAME

SESSION_SECRET=$SESSION_SECRET

EMAIL_MONTHLY_CAP=280
IN_DEVELOPMENT=true

# --- fill in when ready (see .env.example for the full annotated list) ---
GOOGLE_CLIENT_ID=
RESEND_API_KEY=
EMAIL_FROM=ENAIH <noreply@eah.warrenwoolf.com>
EMAIL_REPLY_TO=noreply@eah.warrenwoolf.com
PRIVACY_EMAIL=privacy@eah.warrenwoolf.com
CONTACT_EMAIL=contact@enaih.org
PUBLIC_BASE_URL=https://enaih.org
DISCORD_BOT_TOKEN=
DISCORD_STAFF_CHANNEL_ID=
DISCORD_PUBLIC_CHANNEL_ID=
EOF
  chmod 600 "$ENV_FILE"
fi

log "creating MariaDB database + user ($DB_USER on localhost & 127.0.0.1)"
# root uses unix_socket auth on a fresh Ubuntu MariaDB, so `sudo mysql` works.
# Grant to both 'localhost' (socket) and '127.0.0.1' (TCP) so the connection
# matches regardless of MariaDB's name-resolution settings — the eah container
# connects via TCP to 127.0.0.1.
sudo mysql <<SQL
CREATE DATABASE IF NOT EXISTS \`${DB_NAME}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '${DB_USER}'@'localhost' IDENTIFIED BY '${DB_PASSWORD}';
CREATE USER IF NOT EXISTS '${DB_USER}'@'127.0.0.1' IDENTIFIED BY '${DB_PASSWORD}';
ALTER USER '${DB_USER}'@'localhost' IDENTIFIED BY '${DB_PASSWORD}';
ALTER USER '${DB_USER}'@'127.0.0.1' IDENTIFIED BY '${DB_PASSWORD}';
GRANT ALL PRIVILEGES ON \`${DB_NAME}\`.* TO '${DB_USER}'@'localhost';
GRANT ALL PRIVILEGES ON \`${DB_NAME}\`.* TO '${DB_USER}'@'127.0.0.1';
FLUSH PRIVILEGES;
SQL

# ---- 5. cloudflared (binary + systemd service) -----------------------------
if ! command -v cloudflared >/dev/null 2>&1; then
  log "installing cloudflared (Cloudflare apt repo)"
  sudo mkdir -p --mode=0755 /usr/share/keyrings
  curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg \
    | sudo tee /usr/share/keyrings/cloudflare-main.gpg >/dev/null
  echo "deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared any main" \
    | sudo tee /etc/apt/sources.list.d/cloudflared.list >/dev/null
  sudo apt-get update -y
  sudo apt-get install -y cloudflared
else
  log "cloudflared already present — skipping install"
fi

if [[ -n "$TUNNEL_TOKEN" ]]; then
  log "installing cloudflared as a systemd service"
  # Re-running 'service install' fails if already installed; tolerate that.
  sudo cloudflared service install "$TUNNEL_TOKEN" || \
    echo "  (service already installed — leaving it; reconfigure in the dashboard)"
  sudo systemctl enable --now cloudflared || true
else
  echo
  echo "TUNNEL_TOKEN not set — cloudflared binary installed but no service."
  echo "Create a remote-managed tunnel in the Cloudflare dashboard, then:"
  echo "    sudo cloudflared service install <token>"
fi

# ---- done ------------------------------------------------------------------
log "host bootstrap complete"
cat <<DONE

Next steps:
  1. In the Cloudflare tunnel config, route hostnames to local services:
       app.enaih.org  ->  http://localhost:8090
       ssh.enaih.org  ->  ssh://localhost:22     (put Cloudflare Access in front)
  2. From your laptop, add an SSH alias (~/.ssh/config):
       Host enaih
           HostName ssh.enaih.org
           User ubuntu
           ProxyCommand cloudflared access ssh --hostname %h
  3. Deploy the app:
       DEPLOY_HOST=enaih ./deploy.sh
  4. One-time, seed the bootstrap admin (inside ~/eah on the box):
       ADMIN_BOOTSTRAP_USER=... ADMIN_BOOTSTRAP_EMAIL=... ADMIN_BOOTSTRAP_PASS=... \\
         docker compose run --rm eah bun scripts/seed-admin.ts

DB password + SESSION_SECRET were written to $ENV_FILE (chmod 600). Keep a copy.
DONE
